apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-web-content
  namespace: week4-gitops
  labels:
    app: gitops-web
    owner: platform
data:
  index.html: |
    <!doctype html>
    <html>
      <head><title>W4D5 GitOps</title></head>
      <body>
        <h1>W4D5 GitOps App</h1>
        <p>version: v1</p>
      </body>
    </html>
